KNOWN_FIRST_LINES = {
    "                   GNU LESSER GENERAL PUBLIC LICENSE": "deprecated_LGPL-3.0+",
    " ---- Part 1: CMU/UCD copyright notice: (BSD like) ----- ": "Net-SNMP",
    " FREE SOFTWARE LICENSING AGREEMENT CeCILL ": "CECILL-1.1",
    "\"THE BEER-WARE LICENSE\" (Revision 42):  <phk@FreeBSD.ORG> wrote this file. As long as you retain this notice you  can do whatever you want with this stuff. If we meet some day, and you think  this stuff is worth it, you can buy me a beer in return Poul-Henning Kam": "Beerware",
    "(C) 1988, 1989 by Adobe Systems Incorporated. All rights reserved.   ": "Afmparse",
    "1. You may make and give away verbatim copies of the source form of the software without restriction, provided that you duplicate all of the original copyright notices and associated disclaimers.": "Ruby",
    "1. you can do what you want with it": "diffmark",
    "3DFX GLIDE Source Code General Public License ": "Glide",
    "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.": "dvipdfm",
    "ACPI - Software License Agreement": "Intel-ACPI",
    "ADAPTIVE PUBLIC LICENSE": "APL-1.0",
    "AFFERO GENERAL PUBLIC LICENSE": "AGPL-1.0",
    "ANTLR 2 License": "ANTLR-PD",
    "Academic Free License (\u201cAFL\u201d) v. 3.0 ": "AFL-3.0",
    "Adobe Systems Incorporated(r) Source Code License Agreement ": "Adobe-2006",
    "Aladdin Free Public License": "Aladdin",
    "Allegro 4 (the giftware license)": "Giftware",
    "Apache License": "Apache-2.0",
    "Apache License 1.1 ": "Apache-1.1",
    "Apple Public Source License Ver. 1.2": "APSL-1.2",
    "Attribution Assurance License": "AAL",
    "BSD Protection License ": "BSD-Protection",
    "BSD-4-Clause (University of California-Specific)": "BSD-4-Clause-UC",
    "Before we get to the text of the license, lets just review what the license says in simple terms:": "ImageMagick",
    "Bison Exception": "deprecated_GPL-2.0-with-bison-exception",
    "Boost Software License - Version 1.0 - August 17th, 2003": "BSL-1.0",
    "CNRI OPEN SOURCE GPL-COMPATIBLE LICENSE AGREEMENT": "CNRI-Python-GPL-Compatible",
    "CNRI OPEN SOURCE LICENSE AGREEMENT": "CNRI-Python",
    "CONTRAT DE LICENCE DE LOGICIEL LIBRE CeCILL-B": "CECILL-B",
    "CONTRAT DE LICENCE DE LOGICIEL LIBRE CeCILL-C": "CECILL-C",
    "COPYRIGHT": "mpich2",
    "COPYRIGHT NOTICE   ": "Bahyph",
    "COPYRIGHT NOTIFICATION": "DSDP",
    "CUA Office Public License Version 1.0": "CUA-OPL-1.0",
    "Caldera International, Inc. hereby grants a fee free license that includes the rights use, modify and distribute this named source code, including creating derived binary products created from the source code. The source code for which Caldera International, Inc. grants rights are limited to the following UNIX Operating Systems that operate on the 16-Bit PDP-11 CPU and early versions of the 32-Bit UNIX Operating System, with specific exclusion of UNIX System III and UNIX System V and successor operating systems:": "Caldera",
    "Code derived from the document \"Report on the Programming Language": "HaskellReport",
    "Common Public Attribution License Version 1.0 (CPAL)": "CPAL-1.0",
    "Common Public License Version 1.0": "CPL-1.0",
    "Computer Associates Trusted Open Source License": "CATOSL-1.1",
    "Condor Public License": "Condor-1.1",
    "Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved.  This file is offered as-is, without any warranty.": "FSFAP",
    "Creative Commons Attribution 1.0": "CC-BY-1.0",
    "Creative Commons Attribution 2.0": "CC-BY-2.0",
    "Creative Commons Attribution 2.5": "CC-BY-2.5",
    "Creative Commons Attribution 3.0 Unported": "CC-BY-3.0",
    "Creative Commons Attribution 4.0 International": "CC-BY-4.0",
    "Creative Commons Attribution-NoDerivatives 4.0 International": "CC-BY-ND-4.0",
    "Creative Commons Attribution-NoDerivs 1.0": "CC-BY-ND-1.0",
    "Creative Commons Attribution-NoDerivs 2.0": "CC-BY-ND-2.0",
    "Creative Commons Attribution-NoDerivs 2.5": "CC-BY-ND-2.5",
    "Creative Commons Attribution-NoDerivs 3.0 Unported": "CC-BY-ND-3.0",
    "Creative Commons Attribution-NoDerivs-NonCommercial 1.0": "CC-BY-NC-ND-1.0",
    "Creative Commons Attribution-NonCommercial 1.0": "CC-BY-NC-1.0",
    "Creative Commons Attribution-NonCommercial 2.0": "CC-BY-NC-2.0",
    "Creative Commons Attribution-NonCommercial 2.5": "CC-BY-NC-2.5",
    "Creative Commons Attribution-NonCommercial 3.0 Unported": "CC-BY-NC-3.0",
    "Creative Commons Attribution-NonCommercial 4.0 International": "CC-BY-NC-4.0",
    "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International": "CC-BY-NC-ND-4.0",
    "Creative Commons Attribution-NonCommercial-NoDerivs 2.0": "CC-BY-NC-ND-2.0",
    "Creative Commons Attribution-NonCommercial-NoDerivs 2.5": "CC-BY-NC-ND-2.5",
    "Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported": "CC-BY-NC-ND-3.0",
    "Creative Commons Attribution-NonCommercial-ShareAlike 1.0": "CC-BY-NC-SA-1.0",
    "Creative Commons Attribution-NonCommercial-ShareAlike 2.0": "CC-BY-NC-SA-2.0",
    "Creative Commons Attribution-NonCommercial-ShareAlike 2.5": "CC-BY-NC-SA-2.5",
    "Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported": "CC-BY-NC-SA-3.0",
    "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International": "CC-BY-NC-SA-4.0",
    "Creative Commons Attribution-ShareAlike 1.0": "CC-BY-SA-1.0",
    "Creative Commons Attribution-ShareAlike 2.0": "CC-BY-SA-2.0",
    "Creative Commons Attribution-ShareAlike 2.5": "CC-BY-SA-2.5",
    "Creative Commons Attribution-ShareAlike 3.0 Unported": "CC-BY-SA-3.0",
    "Creative Commons Attribution-ShareAlike 4.0 International": "CC-BY-SA-4.0",
    "Creative Commons CC0 1.0 Universal": "CC0-1.0",
    "Crystal Stacker is freeware. This means you can pass copies around freely provided you include this document in it's original form in your distribution. Please see the \"Contacting Us\" section of this document if you need to contact us for any reason.": "CrystalStacker",
    "Cube game engine source code, 20 dec 2003 release.": "Cube",
    "Deutsche Freie Software Lizenz": "D-FSL-1.0",
    "EGENIX.COM PUBLIC LICENSE AGREEMENT ": "eGenix",
    "ERLANG PUBLIC LICENSE Version 1.1": "ErlPL-1.1",
    "EU DataGrid Software License": "EUDatagrid",
    "Eclipse Public License - v 1.0": "EPL-1.0",
    "Educational Community License": "ECL-2.0",
    "Eiffel Forum License, version 1": "EFL-1.0",
    "Eiffel Forum License, version 2": "EFL-2.0",
    "Entessa Public License Version. 1.0": "Entessa",
    "European Union Public Licence V. 1.1": "EUPL-1.1",
    "European Union Public Licence V.1.0 ": "EUPL-1.0",
    "Fair License": "Fair",
    "FreeImage Public License - Version 1.0": "FreeImage",
    "GL2PS LICENSE Version 2, November 2003": "GL2PS",
    "GNU AFFERO GENERAL PUBLIC LICENSE": "AGPL-3.0",
    "GNU GENERAL PUBLIC LICENSE ": "GPL-1.0",
    "Historical Permission Notice and Disclaimer": "HPND",
    "IBM Public License Version 1.0": "IPL-1.0",
    "ICU License - ICU 1.8.1 and later": "ICU",
    "INTERBASE PUBLIC LICENSE": "Interbase-1.0",
    "IPA Font License Agreement v1.0 ": "IPA",
    "ISC License:": "ISC",
    "Imlib2 License": "Imlib2",
    "Independent JPEG Group License ": "IJG",
    "Info-ZIP License": "Info-ZIP",
    "JSON License": "JSON",
    "JasPer License Version 2.0": "JasPer-2.0",
    "LICENSE FOR THE Extreme! Lab PullParser ": "xpp",
    "LaTeX Project Public License ": "LPPL-1.0",
    "Lesser General Public License For Linguistic Resources": "LGPLLR",
    "Licence Art Libre": "LAL-1.2",
    "Licence Art Libre 1.3 (LAL 1.3)": "LAL-1.3",
    "Licence Libre du Qu\u00e9bec \u2013 Permissive (LiLiQ-P)": "LiLiQ-P-1.1",
    "Licence Libre du Qu\u00e9bec \u2013 R\u00e9ciprocit\u00e9 (LiLiQ-R)": "LiLiQ-R-1.1",
    "Licence Libre du Qu\u00e9bec \u2013 R\u00e9ciprocit\u00e9 forte (LiLiQ-R+)": "LiLiQ-Rplus-1.1",
    "Lucent Public License Version 1.0": "LPL-1.0",
    "Lucent Public License Version 1.02 ": "LPL-1.02",
    "MIT License": "MIT",
    "MOTOSOTO OPEN SOURCE LICENSE - Version 0.9.1": "Motosoto",
    "MakeIndex Distribution Notice": "MakeIndex",
    "Microsoft Public License (Ms-PL)": "MS-PL",
    "Microsoft Reciprocal License (Ms-RL)": "MS-RL",
    "MirOS License": "MirOS",
    "Multics License": "Multics",
    "NASA OPEN SOURCE AGREEMENT VERSION 1.3": "NASA-1.3",
    "NAUMEN Public License ": "Naumen",
    "NETHACK GENERAL PUBLIC LICENSE": "NGPL",
    "NETIZEN OPEN SOURCE LICENSE ": "NOSL",
    "NETSCAPE PUBLIC LICENSE\u2028Version 1.0": "NPL-1.0",
    "NRL License": "NRL",
    "NTP License (NTP)": "NTP",
    "Netscape Public LIcense version 1.1": "NPL-1.1",
    "Nokia Open Source License (NOKOS License) ": "Nokia",
    "Non-Profit Open Software License 3.0": "NPOSL-3.0",
    "Norwegian Licence for Open Government Data (NLOD)": "NLOD-1.0",
    "Noweb is copyright 1989-2000 by Norman Ramsey. All rights reserved.": "Noweb",
    "OCLC Research Public License 2.0": "OCLC-2.0",
    "ODC Open Database License (ODbL)": "ODbL-1.0",
    "OPEN PUBLIC LICENSE ": "OPL-1.0",
    "ORIGINAL LICENSE: This software is": "xinetd",
    "OSET Public License\u2028": "OSET-PL-2.1",
    "Open Data Commons - Public Domain Dedication & License (PDDL)": "PDDL-1.0",
    "Open Software License v. 3.0 (OSL-3.0)": "OSL-3.0",
    "Open Software Licensev. 2.0": "OSL-2.0",
    "OpenSSL License": "OpenSSL",
    "PS Utilities Package": "psutils",
    "PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2 ": "Python-2.0",
    "PostgreSQL Database Management System": "PostgreSQL",
    "Rdisc (this program) was developed by Sun Microsystems, Inc. and is  provided for unrestricted use provided that this legend is included on  all tape media and as a part of the software program in whole or part.  Users may copy or modify Rdisc without charge, and they may freely  distribute it.   ": "Rdisc",
    "RealNetworks Public Source License Version 1.0": "RPSL-1.0",
    "Reciprocal Public License 1.5 (RPL1.5)": "RPL-1.5",
    "Reciprocal Public License, version 1.1": "RPL-1.1",
    "Red Hat eCos Public License v1.1": "RHeCos-1.1",
    "SCEA Shared Source License 1.0": "SCEA",
    "SENDMAIL LICENSE ": "Sendmail",
    "STORAGE NETWORKING INDUSTRY ASSOCIATION ": "SNIA",
    "SUGARCRM PUBLIC LICENSE": "SugarCRM-1.1.3",
    "SUN INDUSTRY STANDARDS SOURCE LICENSE": "SISSL-1.2",
    "SUN PUBLIC LICENSE Version 1.0": "SPL-1.0",
    "Secure Messaging Protocol (SMP) Libraries [ACL, CML, SFL]": "SMPPL",
    "Simple Public License (SimPL)": "SimPL-2.0",
    "Software License for MTL": "MTLL",
    "Steps to update the SPDX License List on the spdx.org website:": "Updating the SPDX Licenses",
    "Sun Industry Standards Source License - Version 1.1": "SISSL",
    "THE FRAMEWORX OPEN LICENSE 1.0": "Frameworx-1.0",
    "THE Q PUBLIC LICENSE version 1.0": "QPL-1.0",
    "TORQUE v2.5+ Software License v1.1 ": "TORQUE-1.1",
    "The \"Artistic License\"": "Artistic-1.0-Perl",
    "The Academic Free License": "AFL-2.0",
    "The Academic Free License ": "AFL-2.1",
    "The Artistic License 2.0": "Artistic-2.0",
    "The Clarified Artistic License": "ClArtistic",
    "The Clear BSD License": "BSD-3-Clause-Clear",
    "The Code Project Open License (CPOL) 1.02": "CPOL-1.02",
    "The Educational Community License": "ECL-1.0",
    "The FreeType Project LICENSE ": "FTL",
    "The Net Boolean Public License": "NBPL-1.0",
    "The Open Group Test Suite License": "OGTSL",
    "The Open Software License v. 1.0": "OSL-1.0",
    "The Open Software License v. 1.1": "OSL-1.1",
    "The Open Software Licensev. 2.1": "OSL-2.1",
    "The PHP License, version 3.0 ": "PHP-3.0",
    "The PHP License, version 3.01": "PHP-3.01",
    "The SFL License Agreement": "iMatix",
    "The TMate Open Source License. ": "TMate",
    "The X.Net, Inc. License": "Xnet",
    "The Zend Engine License, version 2.00 ": "Zend-2.0",
    "The eCos license version 2.0": "deprecated_eCos-2.0",
    "The source code in this package is copyright 1999-2010 by Andrew Plotkin.": "Glulxe",
    "This FastCGI application library source and object code (the \"Software\") and its documentation (the \"Documentation\") are copyrighted by Open Market, Inc (\"Open Market\"). The following terms apply to all files associated with the Software and Documentation unless explicitly disclaimed in individual files.": "OML",
    "This copy of the libpng notices is provided for your convenience.  In case of any discrepancy between this copy and the notices in the file png.h that is included in the libpng distribution, the latter shall prevail.": "Libpng",
    "This file was added by Clea F. Rees on 2008/11/30 with the permission of Dean Guenther and pointers to this file were added to all source files.": "Wsuipa",
    "This git repository contains the SPDX License List data used internally by the SPDX legal team to maintain the license license available at http://spdx.org/licenses and in the Github repository spdx/license-list-data.": "README",
    "This is APREAMBL.TEX, version 1.10e, written by Hans-Hermann Bode ": "Abstyles",
    "This is a package of commutative diagram macros built on top of Xy-pic  by Michael Barr (email: barr@barrs.org). Its use is unrestricted. It  may be freely distributed, unchanged, for non-commercial or commercial  use. If changed, it must be renamed. Inclusion in a commercial  software package is also permitted, but I would appreciate receiving a  free copy for my personal examination and use. There are no guarantees  that this package is good for anything. I have tested it with LaTeX 2e,  LaTeX 2.09 and Plain TeX. Although I know of no reason it will not work  with AMSTeX, I have not tested it": "Barr",
    "This is free and unencumbered software released into the public domain.": "Unlicense",
    "This program is free software; you can redistribute it freely.": "XSkat",
    "This program, \"bzip2\", the associated library \"libbzip2\", and all documentation, are copyright (C) 1996-2010 Julian R Seward. All rights reserved.": "bzip2-1.0.6",
    "This software code is made available \"AS IS\" without warranties of any kind. You may copy, display, modify and redistribute the software code either by itself or as incorporated into your code; provided that > you do not remove any proprietary notices. Your use of this software code is at your own risk and you waive any claim against Amazon Digital Services, Inc. or its affiliates with respect to your use of this software code. (c) 2006 Amazon Digital Services, Inc. or its affiliates": "ADSL",
    "This source code has been made available to you by IBM on an AS-IS basis. \u00a0Anyone receiving this source is licensed under IBM copyrights to use it in any way he or she deems fit, including copying it, modifying it, compiling it, and redistributing it either with or without modifications. \u00a0No license under IBM patents or patent applications is to be implied by the copyright license.": "IBM-pibs",
    "This work is being provided by the copyright holders under the following license.": "W3C-20150513",
    "Trusster Open Source License version 1.0a (TRUST) copyright (c) 2006 Mike Mintz and Robert Ekendahl. All rights reserved.": "TOSL",
    "Unicode Terms of Use ": "Unicode-TOU",
    "University of Illinois/NCSA Open Source License ": "NCSA",
    "VIM LICENSE": "Vim",
    "VOSTROM Public License for Open Source ": "VOSTROM",
    "Version 1.0.5 of 10 December 2007": "bzip2-1.0.5",
    "Vovida Software License v. 1.0 ": "VSL-1.0",
    "W3C SOFTWARE NOTICE AND LICENSE": "W3C",
    "W3C\u00ae SOFTWARE NOTICE AND LICENSE": "W3C-19980720",
    "X11 License": "X11",
    "XFree86 License (version 1.1)": "XFree86-1.1",
    "Yahoo! Public License, Version 1.0 (YPL)": "YPL-1.0",
    "Yahoo! Public License, Version 1.1 (YPL)": "YPL-1.1",
    "Zimbra Public License, Version 1.3 (ZPL)": "Zimbra-1.3",
    "Zimbra Public License, Version 1.4 (ZPL)": "Zimbra-1.4",
    "Zope Public License (ZPL) Version 1.1": "ZPL-1.1",
    "Zope Public License (ZPL) Version 2.0": "ZPL-2.0",
    "Zope Public License (ZPL) Version 2.1": "ZPL-2.1",
    "gSOAP Public License": "gSOAP-1.3b",
    "insert GPL v2 text here": "deprecated_GPL-2.0-with-GCC-exception",
    "insert GPL v3 text here": "deprecated_GPL-3.0-with-autoconf-exception",
    "psfrag.dtx ": "psfrag",
    "wxWindows Library Licence, Version 3.1 ": "deprecated_WXwindows",
    "zlib License": "Zlib",
    "\ufeffinsert GPL v2 text here": "deprecated_GPL-2.0-with-font-exception",
    "\ufeffinsert GPL v3 text here": "deprecated_GPL-3.0-with-GCC-exception",
    "Academic Free License": {
        "Version 1.2 ": "AFL-1.2"},
    "BitTorrent Open Source License": {
        "Version 1.0": "BitTorrent-1.0",
        "Version 1.1": "BitTorrent-1.1"
    },
    "GNU GENERAL PUBLIC LICENSE": {
        "Version 3, 29 June 2007": "deprecated_GPL-3.0+"
    },
    "MOZILLA PUBLIC LICENSE": {
        "Version 1.0": "MPL-1.0"
    },
    "Mozilla Public License Version 2.0 ": "MPL-2.0-no-copyleft-exception"
}

DISCRIMINENT_PATTERNS = {
    'This configure script is free software; the Free Software Foundation gives unlimited permission to copy, distribute and modify it.': 'FSFUL',
    'You may copy and distribute this file freely.  Any queries and complaints should be forwarded to ': 'Zed',
    'training or assistance of any kind with regard to the use': 'NetCDF',
    'Permission to use, copy, modify, distribute, and sell this software and its documentation for any purpose is hereby granted without fee': 'libtiff'

}

OTHER_LICENSES = {
    'zlib': """This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment (see the following) in the product documentation is required.

2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
"""

}
